version: '3.9'

services:
    web:
        build: .
        container_name: "django"
        command: python /shop/myshop/manage.py runserver  --insecure 0.0.0.0:8000
        # command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
        volumes:
        - static_volume:/shop/staticfiles
        - media_volume:/shop/myshop/media
        ports:
            - 8000:8000
        depends_on:
        - db_shop
        env_file:
            - .env
    db_shop:
        image: postgres:15
        container_name: "POSTGRES_DB"
        volumes:
        - pg_shop:/var/lib/postgresql/data/

        environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    # nginx:
    #     image: nginx
    #     container_name: "nginx"
    #     volumes:
    #     - static_volume:/shop/static
    #     - media_volume:/shop/media
    #     - ./nginx-conf.d:/etc/nginx/conf.d
    #     depends_on:
    #         - web
    #     ports:
    #         - 80:80

volumes:
    pg_shop:
    static_volume:
    media_volume:
