version: '3.9'

services:
    web:
        restart: always
        build: .
        container_name: "django"
        command: bash entrypoint.sh
        # command: python /shop/myshop/manage.py runserver  --insecure 0.0.0.0:8000
        # command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
        volumes:
        - static_volume:/shop/staticfiles
        - media_volume:/shop/myshop/media
        ports:
            - 8000:8000
        depends_on:
        - db_shop
        - rabbitmq
        env_file:
            - .env
    db_shop:
        restart: always
        image: postgres:15
        container_name: "POSTGRES_DB"
        volumes:
        - pg_shop:/var/lib/postgresql/data/

        environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
    # nginx:
    #     image: nginx
    #     container_name: "nginx"
    #     volumes:
    #     - static_volume:/shop/static
    #     - media_volume:/shop/media
    #     - ./nginx-conf.d:/etc/nginx/conf.d
    #     depends_on:
    #         - web
    #     ports:
    #         - 80:80
    rabbitmq:
        restart: always
        image: rabbitmq:3.12-management
        container_name: "rabbitmq"
        environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        ports:
        - "5672:5672"
        - "15672:15672"
    celery:
        restart: always
        build: .
        container_name: 'celery'
        command: bash celery.sh
        env_file:
        - .env
        depends_on:
        - web
        - db_shop
        - rabbitmq

volumes:
    pg_shop:
    static_volume:
    media_volume:
